---

- name: Update VM's to portgroup
  hosts: vc1
  connection: local
  gather_facts: no

  vars:
    switch: VMware-VMM
    vms:
    - name: RedHat_Demo-app
      portgroup: quarantine
    - name: RedHat_Demo-db
      portgroup: quarantine
    - name: RedHat_Demo-web
      portgroup: quarantine

  tasks:
  - name: Update VMs to quarantine
    vmware_guest:
     hostname: "{{ host }}"
     username: "{{ user }}"
     password: "{{ pass }}"
     datacenter: DATA
     validate_certs: no
     name: "{{ item.name }}"
     state: absent
#     networks:
#     - name: "{{ item.portgroup }}"
    delegate_to: localhost
    loop: "{{ vms }}"

- name: Cleanup MSO
  hosts: mso1
  connection: local
  gather_facts: no

  vars:
    tenant: RedHat_Ansible
    schema: RedHat Demo
    template: RedHat Template 1
    template2: RedHat Template 2
    vrf: vrf1
    bd: bd1
    ap: ap1
    epg1: db
    epg2: web
    epg3: app
    contract1: web2app
    contract2: app2db
    filter1: filter1
    filter2: filter2
    mso_login: &mso_login
     host: "{{ host }}"
     username: "{{ user }}"
     password: "{{ pass }}"
     validate_certs: no

  tasks:
  - name: Undeploy a schema template
    mso_schema_template_deploy:
     <<: *mso_login
     schema: "{{ schema }}"
     template: "{{ template }}"
     site: On-premises
     state: undeploy
    delegate_to: localhost
  - name: Undeploy a schema template
    mso_schema_template_deploy:
     <<: *mso_login
     schema: "{{ schema }}"
     template: "{{ template2 }}"
     site: AWS-West
     state: undeploy
    delegate_to: localhost
  - name: Remove schema
    mso_schema:
     <<: *mso_login
     schema: "{{ schema }}"
     state: absent
    delegate_to: localhost
  - name: Remove a tenant
    mso_tenant:
     <<: *mso_login
     tenant: RedHat Ansible
     state: absent
    delegate_to: localhost
